// SAO Version
// Author(s):       AliAssassiN <ailsynthax@gmail.com>
//
// Copyright (c) 2015-2016 The San Andreas Online Open Source Project
//
// Distributed under the MIT license (See accompanying file LICENSE or copy at
// https://opensource.org/licenses/MIT)

#include "Version.h"

#define SAO_CONCAT(a,b) a##b
#define SAO_STRINGIZE_(x) #x
#define SAO_STRINGIZE(x) SAO_STRINGIZE_(x)

#define SAO_VERSION_DOT SAO_VERSION_MAJOR.SAO_VERSION_MINOR.SAO_VERSION_PATCH.SAO_VERSION_REVISION

#if SAO_VERSION_PATCH == 0
	#define SAO_SHORT_VERSION_DOT SAO_VERSION_MAJOR.SAO_VERSION_MINOR
#else
	#define SAO_SHORT_VERSION_DOT SAO_VERSION_MAJOR.SAO_VERSION_MINOR.SAO_VERSION_PATCH
#endif

#define SAO_VERSION_COMMA SAO_VERSION_MAJOR.SAO_VERSION_MINOR.SAO_VERSION_PATCH.SAO_VERSION_REVISION

#if SAO_VERSION_PATCH == 0
	#define SAO_SHORT_VERSION_COMMA SAO_VERSION_MAJOR,SAO_VERSION_MINOR
#else
	#define SAO_SHORT_VERSION_COMMA SAO_VERSION_MAJOR,SAO_VERSION_MINOR,SAO_VERSION_PATCH
#endif

#define SAO_STRINGVERSION_DOT SAO_STRINGIZE(SAO_VERSION_DOT)
#define SAO_STRINGSHORTVERSION_DOT SAO_STRINGIZE(SAO_SHORT_VERSION_DOT)

#define SAO_STRINGVERSION_COMMA COMMA_STRINGIZE(SAO_VERSION_COMMA)
#define SAO_STRINGSHORTVERSION_COMMA SAO_STRINGIZE(SAO_SHORT_VERSION_COMMA)
